# Python : NumPy
[Pure Python, NumPy, Pandas, and TensorFlow]

numpy == Numarical Python

Python is a "dynamically typed" programming language.

list는 데이터의 값과 타입까지 모두 저장을 하는 특징이 있다.

유연하고, 많은 양을 저장할 수 있다.

때문에 타입도 고려해야하고, 저장용량과 시간을 많이 소모한다.

넘파이는 리스트의 이러한 단점을 보완하기 위해 만들어진 라이브러리이다.

특히 숫자데이터 처리에 특화되어있다

Numpy keeps "the same type of data in arrays"

TensorFlow는 연산과정을 그래프화하여 시각화할 수 있다.
TensorFlow는 값의 변화 과정을 시각화하여 관찰할 수 있다.
"The computational graph approach, TensorFlow"

PanDas == Panel Data

pandas는 빅데이터 환경과 같이 많은 데이터를 효율적으로 처리할 수 있다

__1. NumPy : type, dtype, shape, dimension, size__
- Data types are the same in an array.
- Rank : the (linearly independent) number of variables in a matrix.

In [2]:
#넘파이는 수치연산에 특화되어있다
import numpy as np
a = np.array([7,8,9,10,11])
b = [7,8,9,10,11]; print(b) #리스트
#어레이의 모든 요소는 같은 사이즈(같은 크기의 공간을 차지)로 이루어져있다
#가장 큰 사이즈의 크기로 모든 값에 할당하다 보니, 출력값의 띄어쓰기가 이상이상
print(f'{a}\n{"object type:":>12}) {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12} \
{a.shape}\n{"dimension:":>12} {a.ndim}\n{"array size:":>12} {a.size}')
a1 = np.array([a]); print(a1.shape)
print(a1) 
#대괄호의 개수를 통해 데이터의 차원을 파악할 수 있다
#shape안에 숫자의 개수는 차원의 개수를 나타낸다
#(1, 5)의 의미 == 행 5열의 2차원배열

[7, 8, 9, 10, 11]
[ 7  8  9 10 11]
object type:) <class 'numpy.ndarray'>
  data type: int32
      shape: (5,)
  dimension: 1
 array size: 5
(1, 5)
[[ 7  8  9 10 11]]


In [6]:
b = np.array([[1.0,2,3,4,5],[8,9,10,11,12.2]])
#1.0덕분에 모두 유리수화, 같은 공간 차지
print(f'{b}\n{"object type:":>12}) {type(b)}\n{"data type:":>12} {b.dtype}\n{"shape:":>12} \
{b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12} {b.size}')
b1 = np.array([b]); print(b1.shape)

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type:) <class 'numpy.ndarray'>
  data type: float64
      shape: (2, 5)
  dimension: 2
 array size: 10
(1, 2, 5)


In [6]:
c = np.array([[[1,2,3,4,5],[8,9,10,11,12]],[[4,5,6,7,8],[10,11,12,13,14]]])
print(f'{c}\n{"object type:":>12}) {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12} \
{c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')
c1 = np.array([c]); print(c1.shape)
#shape은 3차원, 2, 2, 5을 표시
#dimension : 3

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type:) <class 'numpy.ndarray'>
  data type: int32
      shape: (2, 2, 5)
  dimension: 3
 array size: 20
(1, 2, 2, 5)


In [10]:
ac1 = np.array([[[1,2,3,4,5],[8,9,10,11,12]]])
print(f'{ac1}\n{"object type:":>12}) {type(ac1)}\n{"data type:":>12} {ac1.dtype}\n{"shape:":>12} \
{ac1.shape}\n{"dimension:":>12} {ac1.ndim}\n{"array size:":>12} {ac1.size}')

#3차원에 1개의 벡터가 존재한다(이래서 헷갈림))


[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type:) <class 'numpy.ndarray'>
  data type: int32
      shape: (1, 2, 5)
  dimension: 3
 array size: 10


__2. Numpy:special arrays and indexing__
- 하나의 Numpy 배열은 하나의 데이터 타입만을 가질 수 있다

In [4]:
a_zeros = np.zeros((2,3)) #0으로만 이루어진 행렬
print(a_zeros)
a_ones = np.ones((2,4) , dtype=int) #1로만 이루어진 행렬
print(a_ones)
a_full = np.full((2,5),7) #어떤 숫자로든지, 지명만 하면 꽉 채워준다
print(a_full)
print(np.eye(3)) #eye = 단위행렬(identity matrix)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a_ran = np.random.random((2,3,4)) #2개의 행렬에 3행 4열 을 랜덤하게
print(f'{a_ran}\n{a_ran.dtype}')

#random은 0포함, 1미만

[[[0.36156941 0.77474134 0.0924999  0.81244489]
  [0.55973587 0.7097845  0.3867217  0.17556014]
  [0.52199992 0.1928971  0.45678501 0.89781183]]

 [[0.94006228 0.57794847 0.76301555 0.7880795 ]
  [0.8060596  0.84865695 0.00964268 0.71475056]
  [0.71904663 0.78433024 0.49779394 0.9805822 ]]]
float64


In [8]:
print(c)
print(c[0,0,0])
print(c[0,0,1])
print(c[0,0,4])
print(c[1,0,4])
print(c[1,1,1])

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
1
2
5
8
11


__3. NumPy : flattening and making arrays with arrange function__
- flattening은 다차원 배열을 일차원 배열로 변환해주는 함수이다

In [32]:
print(c)
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')
print()
#flattening
print(np.array(c.flat))

#list는 콤마와 스페이스로, 넘파이어레이는 스페이스로 요소를 구분하여 보여준다

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]

[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [10]:
#arange를 array로 바꾸기 == reshape
#arange는 1차원의 배열(not list), reshape을 통해 차원을 형성할 수 있다
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [8]:
h = np.arange(5, 21, 2) #어레인지는 단순히 처음과 끝, 구간을 설정하는 것
print(h)
print(np.arange(1, 21).reshape(2,10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [10]:
a_ss = np.linspace(0,1,11) #linspace는 마지막 숫자를 포함한다
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


In [18]:
seven = np.array([[[1,2,3,4,5]]])
print(seven.flat == seven.reshape(5,))

[ True  True  True  True  True]


__4. NumPy : Array operations__
- Operations on all elements of arrays

In [21]:
#배열의 차원이 완전히 일치하는 경우 element-wise연산이 가능하다
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [24]:
print(np.add(xa,xb)) #더하기
print()
print(np.subtract(xa,xb)) #빼기
print()
print(np.multiply(xa,xb)) #곱하기
print()
print(np.sqrt(xa)) #?

[[ 4  6]
 [ 8 10]
 [12 14]]

[[-2 -2]
 [-2 -2]
 [-2 -2]]

[[ 3  8]
 [15 24]
 [35 48]]

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [26]:
#행렬의 inner product연산의 경우 두 행렬의 정합성이 맞아야 한다
xc = np.ones((2,1))
print(xc, xc.shape, xc.ndim)
print()
print(xa.dot(xc)) #xa = 3x2, xc = 2x1 이므로 둘을 합(dot)하면 3x1이 나온다
print()
print(np.dot(xb,xc) #dot() as a method

[[1.]
 [1.]] (2, 1) 2

[[ 3.]
 [ 7.]
 [11.]]

[[ 7.]
 [11.]
 [15.]]


In [27]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa,xd));print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [30]:
print(xa)
print(xa.T) # T는 Transposed, 전치행렬 3x2 -> 2x3으로
print()
print(xb+3)
print(xb) #원래 xb는 남아있는 상태
xb += 3
print(xb) #xb의 값이 바뀜

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]

[[12 13]
 [14 15]
 [16 17]]
[[ 9 10]
 [11 12]
 [13 14]]
[[12 13]
 [14 15]
 [16 17]]


__5. NumPy : Broadcasting__
- Arithmetic operation between different shaped arrays

In [36]:
ya = np.arange(1,10).reshape(3,3); print(ya)
print()
yv1 = np.ones((3,1)); print(yv1)
print()
yb = ya + yv1 ; print(yb) #dimension이 틀려도 broadcasting rule이 적용되면 계산가능
print()
yv2 = np.full((1,3),2); print(yv2)
print()
yc = ya + yv2; print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1.]
 [1.]
 [1.]]

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

[[2 2 2]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


__6. NumPy : Summary Statistics__

In [42]:
print(yc.sum(), yc.mean(), yc.min(), yc.max(), yc.var(), yc.std())
print(yc.argmax(), yc.argmin()) #가장 크고 작은 값의 인덱스 반환
print(yc.mean(axis=0), yc.mean(axis=1)) #0은 열, 1은 행

63 7.0 3 11 6.666666666666667 2.581988897471611
8 0
[6. 7. 8.] [ 4.  7. 10.]


__7.NumPy : Slicing, Flatten, and Stacking__

In [52]:
karray = np.arange(21).reshape(3,7); print(karray)
print()
print(karray[0])
print()
print(karray[0:4])
print()
print(karray[:2]) #콤마가 없을 경우는 row만 인식한다는 것
print()
print(karray[:2,:3]) #2개의 행, 3개의 열

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

[0 1 2 3 4 5 6]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]

[[0 1 2]
 [7 8 9]]


In [58]:
karray = np.arange(21).reshape(3,7); print(karray)
print()
print(karray[[0,2]]) #0과 2의 로우 지정
print()
print(karray[:,[1,5]]) #row는 모두, column은 1과 5만
print()
print(karray[:,1:5]) #row는 모두, column은 1부터5까지

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]

[[ 1  5]
 [ 8 12]
 [15 19]]

[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [69]:
karray = np.arange(21).reshape(3,7); print(karray)
fkarray = karray.flatten() #1차원 어레이로 나열
print()
print(fkarray, fkarray.shape)
print()
fkarray1 = np.array(karray.flat) #아니면 이렇게 해도 됨 np.array보다는 flatten이 편함
print(fkarray1)
print()
rfkarray = karray.reshape(1,21) #reshape으로 어레이의 차원 변경 가능
print(rfkarray, rfkarray.shape)
print()
rfkarray.resize(3,7) #새로운 형태로 변형
print(rfkarray, rfkarray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]] (1, 21)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [74]:
#stacking
karray1 = karray[:,:3]; karray2 = karray[:,3:6]
karrayh = np.hstack([karray1, karray2]); print(karrayh) #가로로 쌓기
print()
karrayv = np.vstack([karray1, karray2]); print(karrayv) #세로로 쌓기

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]]

[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [ 3  4  5]
 [10 11 12]
 [17 18 19]]


In [83]:
A = np.full((3,2),3)
B = np.ones((2,1))
print(A)
print(B)
A.dot(B)
A.size
B.size
A+1

array([[4, 4],
       [4, 4],
       [4, 4]])

In [99]:
Array1 = np.array([[1,2],[3,4],[5,6]])
Array1.resize(2,3)
Array1.shape
Array1.argmax()

5